### ISSUE TITLE
Try Yoursself Snippets are not working

### ISSUE THREAD

**Issue by 99Pp** [riuandg5/learn-makefile#3]
There are leading spaces in your Try Yourself snippets due to which a user can't run your snippets by simply using the Copy to Clipboard feature

![image](https://user-images.githubusercontent.com/50335521/126027851-34a42dd0-464d-497b-99b9-5d8e513f4413.png)

**Comment by riuandg5** [comment]
@99Pp  First of all, good to know that someone is seeing my efforts. 😁  And secondly, I am already aware of the issue raised by you. It was because of my markdown settings in vscode. This was a mistake and I also encountered it when I was testing my snippet but didn't fix it because I thought it would be nice if someone writes the code by themselves instead of copy pasting it.
It states that we must use strict tab indentation in our Makefiles.
If you want, you can correct it and make a pull request. 😄

**Comment by 99Pp** [comment]
Ya I was thinking of making a PULL request..Lest make it the "Perfect Makefile :Noob to Pro"
